### ISSUE TITLE
How to connect FH-L550 with FH-SC05r camera using python

### ISSUE THREAD

**Issue by NguyenDucQuan12** [aphyt/aphytcomm#3]
Hello, I was wandering around github and found the documentation about omron product line written in python by you. So I want to ask how can I get images from FH-SC05R camera using python, I have devices including FH-L550, FH-SC05R, FZ-VS3, S8VK-C12024, CP2E-N40DR-D, . ..
Thank you

**Comment by aphyt** [comment]
The FH vision system is outside of the scope of this library. I understand that the FH has the ability to images to network drives or RAM where they can be retrieved by FTP. Since Python has built in FTP, that is preferable to a new library.

**Comment by NguyenDucQuan12** [comment]
@aphyt Can I ask you something, I want to write a piece of code that can take a picture every time I press a button, and retrieve that image so I can process it. So how can I write code in python on my computer through FH controller
