### ISSUE TITLE
Omron Can't read other  language tag

### ISSUE THREAD

**Issue by yazhoumengnan** [aphyt/aphytcomm#5]
it's error when i read chinese tag.
so i try this  follow:

len(bytes(name.encode("utf-8")))    instead  len(name) 
or 
len(bytearray(name.encode("utf-8")))    instead  len(name) 

def _extended_symbol_segment(name: str):
    request_path_bytes = b'\x91' + len(bytes(name.encode("utf-8"))).to_bytes(1, 'little') + name.encode('utf-8')
    if len(request_path_bytes) % 2 != 0:
        request_path_bytes = request_path_bytes + b'\x00'
    return request_path_bytes

**Comment by aphyt** [comment]
Thank you for your contribution yazhoumengnan! I used Google translate to create tags in Chinese in my Sysmac Studio test project and was able to reproduce your issue and demonstrate that your fix works with Chinese tags as well as passing all current unit tests, so I have merged the changes into version 0.1.21 and it is now available in the main branch as well as on PyPi.
