### ISSUE TITLE
Empty dictionary ?

### ISSUE THREAD

**Issue by ben13300** [aphyt/aphytcomm#8]
Dear, 
When i start my python project with these simple lines

from aphyt import omron
eip_connection = omron.NSeries('10.31.230.31')
eip_connection.update_variable_dictionary()
print(eip_connection.system_variable_list())

i got this following issue
#Traceback (most recent call last):
  File "C:\Users\briviere\PycharmProjects\pythonProject\TEST.py", line 4, in <module>
    eip_connection.update_variable_dictionary()
  File "C:\Users\briviere\PycharmProjects\pythonProject\venv\Lib\site-packages\aphyt\omron\n_series.py", line 319, in update_variable_dictionary
    user_instance_list = self._get_instance_list_subset(True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\briviere\PycharmProjects\pythonProject\venv\Lib\site-packages\aphyt\omron\n_series.py", line 846, in _get_instance_list_subset
    instance_count = struct.unpack('<H', reply.reply_data[0:2])[0]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 2 bytes

must we conclude that the PLC does not make its data dictionary available?

Thank you for your help.

**Comment by aphyt** [comment]
That seems odd to me as I use that same sequence in my test script, but it looks like the PLC is not responding to the 0x6A CIP message. Can you verify the PLC model and that you are able to go online with Sysmac Studio?

**Comment by ben13300** [comment]
Thank you . The device is a CJ2M-EIP21-R2.
I am not allow to connect with the device, because it's under warranty. 
The device is in RUN mode.

**Comment by aphyt** [comment]
This library is written for the NX and NJ series PLCs, so the CJ2M is not a supported platform. It seems that the CJ2M does not have the same CIP services that the NX and NJ have. You could try reading and writing to a published variable without updating the variable dictionary, but it might not work if the read tag and write tag services are different as well. I don't have a CJ system to test this.

**Comment by ben13300** [comment]
OK thank you very much for your help, and congrats for your wonderful job !
